
DROP TABLE IF EXISTS "users";
CREATE TABLE IF NOT EXISTS "users"
(
-- GENERATED BY DEFAULT AS IDENTITY use for @GeneratedValue(strategy = IDENTITY)
--     id     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    id     bigint PRIMARY KEY ,
    name   VARCHAR(255) NOT NULL,
    address    VARCHAR(255) NOT NULL,
    phoneNumber     VARCHAR(255) NOT NULL
);
DROP SEQUENCE IF EXISTS "users_id_seq";
CREATE SEQUENCE "users_id_seq" ;


-- INSERT INTO "users" (id, name, address, phoneNumber)
-- VALUES (11, 'Ivawen', 'address', 'phoneNumber' );
-- INSERT INTO "users" (id, name, address, phoneNumber)
-- VALUES (10, 'Ivqqqan', 'Ivanov', 'Ivanov' );
-- INSERT INTO "users" (id, name, address, phoneNumber)
-- VALUES (12, 'ffff', 'Ivanov', 'Ivanov' );
-- INSERT INTO "users" (id, name, address, phoneNumber)
-- VALUES (14, 'ffff', 'Ivanov', 'Ivanov' );
