--liquibase formatted sql

--changeset metlushkoaa:1
CREATE TABLE IF NOT EXISTS "users"
(
-- GENERATED BY DEFAULT AS IDENTITY use for @GeneratedValue(strategy = IDENTITY)
--     id     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    id     bigint PRIMARY KEY ,
    name   VARCHAR(255) NOT NULL,
    address    VARCHAR(255) NOT NULL,
    phoneNumber     VARCHAR(255) NOT NULL
);
--rollback DROP TABLE "users";

--changeset metlushkoaa:2
CREATE SEQUENCE "users_id_seq" ;
--rollback SEQUENCE "users_id_seq"

--changeset metlushkoaa:3
INSERT INTO "users" (id, name, address, phoneNumber)
VALUES (11, 'Ivawen', 'address', 'phoneNumber' );
INSERT INTO "users" (id, name, address, phoneNumber)
VALUES (10, 'Ivqqqan', 'Ivanov', 'Ivanov' );
INSERT INTO "users" (id, name, address, phoneNumber)
VALUES (12, 'name', 'Ivanov', 'Ivanov' );
INSERT INTO "users" (id, name, address, phoneNumber)
VALUES (14, 'ffff', 'Ivanov', 'Ivanov' );
